language: node_js
node_js:
  - "node"

script:
  - npm test
  - npm run build

deploy:
  provider: surge
  domain: http://tic-tac-toe-mhus25.surge.sh/
  project: ./build/
  skip_cleanup: true
on:
  branch: master
